fieldLayouts:
  8b620cd4-2056-4eed-be86-3fef0fc3ac80:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3dedf05a-331f-4aba-98fc-f4e8f3f03009
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b5f6673b-7b1f-44b9-86d1-ffafc6ddffc2
        userCondition: null
fs: hardDisk
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
