columnSuffix: inceetjb
contentColumnType: text
fieldGroup: 6685a9ec-9ea6-47c3-b853-29ee47ea1c87 # Blog
handle: summary
instructions: 'Summaries should be one or two sentences.'
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 1
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
