defaultPlacement: end
fieldLayouts:
  d90f5eb5-d9f3-4303-9c73-518f46d785cd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: c3e64b3e-4151-4b1a-a1d7-70462e3bc77e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ffaedf1b-addd-4df9-bc57-4a5b1d71e41b
        userCondition: null
handle: topics
name: Topics
siteSettings:
  2562c4d8-3104-460d-bb13-2d88a60cebe9: # McCann Test
    hasUrls: true
    template: blog/_topic
    uriFormat: 'blog/topics/{slug}'
structure:
  maxLevels: 1
  uid: 63cc90c4-a8a2-475a-965f-305125831de9
